baseurl = "/"
languageCode = "en-us"
title = "The Later Glory"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

#remotes::install_github('rstudio/blogdown')

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    
[[menu.main]]
    name = "Visit"
    url = "/visit/" 
    
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    
[[menu.main]]
    name = "Contact"
    url = "/reach us/"
    
[[menu.main]]
    name = "Facebook"
    url = "https://www.facebook.com/latterglory.piacenza.1?epa=SEARCH_BOX"

[[menu.main]]
    name = "You Tube"
    url = "https://www.youtube.com/channel/UC0hE6FK3BZjvmmd74rIInKQ"

#[[menu.main]]
#    name = "Github"
#    url = "https://github.com/seymakalay/Church"





[params]
    description = "A website built through Hugo and blogdown."
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "myCross.png"
    
   

    [params.logo]
    url = "thelater.png"
    width = 700
    height = 150
    alt = "Logo"
    
[params.footer]
    copyright = "The Later Glory Ministiries | Theme modified from <a href=\"https://github.com/kakawait/hugo-tranquilpeak-theme\">Tranquilpeak</a>"

